export const API_ROUTES = {
	activity: {
		findByBoard: (boardId: string) => `/activity/board/${boardId}`,
		findByUser: '/activity/user',
		findByEntity: (entityId: string) => `/activity/entity/${entityId}`,
	},
	auth: {
		register: '/auth/local/register',
		login: '/auth/local/login',
		google: '/auth/social/google',
		passChange: '/auth/password/change',
		passRequest: '/auth/password/request',
		passReset: '/auth/password/reset',
	},
	boards: {
		create: (workspaceId: string) => `/boards/create/${workspaceId}`,
		findOne: (boardId: string) => `/boards/find/one/${boardId}`,
		findByUser: '/boards/find/user',
		updGeneral: (boardId: string) => `/boards/update/general/${boardId}`,
		updSettings: (boardId: string) => `/boards/update/settings/${boardId}`,
		close: (boardId: string) => `/boards/update/close/${boardId}`,
		open: (boardId: string) => `/boards/update/open/${boardId}`,
		starred: (boardId: string) => `/boards/update/starred/${boardId}`,
		addMember: (boardId: string) => `/boards/members/add/${boardId}`,
		removeMember: (boardId: string) => `/boards/members/remove/${boardId}`,
		addAdmin: (boardId: string) => `/boards/admins/add/${boardId}`,
		removeAdmin: (boardId: string) => `/boards/admins/remove/${boardId}`,
		leave: (boardId: string) => `/boards/leave/${boardId}`,
		addList: (boardId: string) => `/boards/lists/add/${boardId}`,
		updList: (boardId: string) => `/boards/lists/update/${boardId}`,
		listsOrder: (boardId: string) => `/boards/lists/order/${boardId}`,
	},
	comments: {
		create: '/comments/create',
		findByTask: (taskId: string) => `/comments/find/task/${taskId}`,
		findByBoard: (boardId: string) => `/comments/find/board/${boardId}`,
		update: (commentId: string) => `/comments/update/${commentId}`,
		delete: (commentId: string) => `/comments/delete/${commentId}`,
	},
	invites: {
		accept: (inviteId: string) => `/invite/accept/${inviteId}`,
		reject: (inviteId: string) => `/invite/reject/${inviteId}`,
		findByEmail: (email: string) => `/invite/find/email?email=${email}`,
		findById: (inviteId: string) => `/invite/find/id/${inviteId}`,
	},
	notes: {
		create: '/notes/create',
		findById: (noteId: string) => `/notes/find/id/${noteId}`,
		findByOwner: '/notes/find/owner',
		update: (noteId: string) => `/notes/update/${noteId}`,
		delete: (noteId: string) => `/notes/delete/${noteId}`,
	},
	tasks: {
		create: (boardId: string) => `/tasks/create/${boardId}`,
		findById: (taskId: string) => `/tasks/find/id/${taskId}`,
		findByUser: '/tasks/find/user',
		updGeneral: (taskId: string) => `/tasks/update/general/${taskId}`,
		updOrder: (boardId: string) => `/tasks/update/order/${boardId}`,
		complete: (taskId: string) => `/tasks/update/complete/${taskId}`,
		archive: (taskId: string) => `/tasks/update/archive/${taskId}`,
		addMember: (taskId: string) => `/tasks/members/add/${taskId}`,
		removeMember: (taskId: string) => `/tasks/members/remove/${taskId}`,
		leave: (taskId: string) => `/tasks/members/leave/${taskId}`,
		addSubtask: (taskId: string) => `/subtasks/add/${taskId}`,
		updSubtask: (taskId: string) => `/subtasks/update/${taskId}`,
		delSubtask: (taskId: string) => `/subtasks/delete/${taskId}`,
	},
	users: {
		updGeneral: 'users/update/general',
		addContact: (contactId: string) => `/users/contacts/add/${contactId}`,
		removeContact: (contactId: string) => `/users/contacts/remove/${contactId}`,
		findContacts: '/users/contacts',
		deleteAccount: '/users/delete/account',
	},
	workspaces: {
		create: '/workspaces/create',
		findById: (workspaceId: string) => `/workspaces/find/one/${workspaceId}`,
		findAll: '/workspaces/find/all',
		updGeneral: (workspaceId: string) => `/workspaces/update/general/${workspaceId}`,
		updSettings: (workspaceId: string) => `/workspaces/update/settings/${workspaceId}`,
		invite: (workspaceId: string) => `/workspaces/members/invite/${workspaceId}`,
		removeMember: (workspaceId: string) => `/workspaces/members/remove/${workspaceId}`,
		addAdmin: (workspaceId: string) => `/workspaces/admins/add/${workspaceId}`,
		removeAdmin: (workspaceId: string) => `/workspaces/admins/remove/${workspaceId}`,
		leave: (workspaceId: string) => `/workspaces/leave/${workspaceId}`,
		delete: (workspaceId: string) => `/workspaces/delete/${workspaceId}`,
	},
};
